<project xmlns="http://maven.apache.org/POM/4.0.0"
         xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
         xsi:schemaLocation="http://maven.apache.org/POM/4.0.0
                             https://maven.apache.org/xsd/maven-4.0.0.xsd">

    <modelVersion>4.0.0</modelVersion>
    <groupId>com.example.hello</groupId>
    <artifactId>hello-soap-osgi</artifactId>
    <version>1.0.0</version>
    <packaging>pom</packaging>

    <modules>
        <module>hello-api</module>
        <module>hello-impl</module>
        <module>hello-runner</module>
    </modules>
</project>
