# Equinox OSGi configuration
osgi.bundles=\
file:../bundles/hello-api-1.0.0.jar@start,\
file:../bundles/hello-impl-1.0.0.jar@start,\
file:../bundles/cxf-core-4.0.4.jar,\
file:../bundles/cxf-rt-frontend-simple-4.0.4.jar,\
file:../bundles/cxf-rt-databinding-aegis-4.0.4.jar,\
file:../bundles/cxf-rt-bindings-soap-4.0.4.jar,\
file:../bundles/cxf-rt-transports-http-4.0.4.jar,\
file:../bundles/cxf-rt-transports-http-jetty-4.0.4.jar,\
file:../bundles/jetty-http-11.0.20.jar,\
file:../bundles/jetty-io-11.0.20.jar,\
file:../bundles/jetty-util-11.0.20.jar,\
file:../bundles/jetty-server-11.0.20.jar,\
file:../bundles/jetty-security-11.0.20.jar,\
file:../bundles/jetty-servlet-11.0.20.jar,\
file:../bundles/jakarta.servlet-api-5.0.0.jar
eclipse.consoleLog=true